### ISSUE TITLE
Unclear readme: how to start a service of a rust process?

### ISSUE THREAD

**Issue by ethereumdegen** [servicer-labs/servicer#10]
I have a rust application that i normally run with 'cargo run' so how can i use servicer with it ?

**Comment by ethereumdegen** [comment]
this is weird hm 

thread 'main' panicked at 'No interpeter found for extension rs. Please provide a custom interpeter and try again.', /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/servicer-0.1.12/src/handlers/handle_create_service.rs:129:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

why cant it assume i am using cargo ?

**Comment by secretshardul** [comment]
You should first build the binary, then run servicer. Do you have a hard requirement to use `cargo run`?  `ser edit` might better help if that's the case.

```sh
cargo build
sudo ser create ./target/release/my-binary
```
