### ISSUE TITLE
arm-compatible binaries

### ISSUE THREAD

**Issue by flexwie** [servicer-labs/servicer#3]
The binary shipped with the release is not arm-compatible. I would like to include servicer in my initial server setup scripts and they are also used on Ampere based CPUs. 
Can you provide an arm binary in the release as well? I would like to avoid installing the whole rust toolchain and building them from scratch on every machine.

Please let me know if you'd like me to contribute some kind of automation for this!

**Comment by secretshardul** [comment]
We could automate the build and artefact upload process with github actions

**Comment by secretshardul** [comment]
Excellent, LGTM
