### ISSUE TITLE
reloading service

### ISSUE THREAD

**Issue by flexwie** [servicer-labs/servicer#6]
continuing the discussion from #5 as the PR is already merged:

> I'm assuming your test is failing because the hello-world example has no [ExecReload](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecReload=) target. Normally it shouldn't require a failed state to reload the configuration of a service.
> 
> I use reload a lot in web server configurations like caddy or nginx.
> 
> Sorry for not checking in with you beforehand, I added this for my use cases and thought someone else might find it useful as well! I agree that not the whole API should be blindly ported. Maybe we can settle on TryReloadOrRestart as a sensible default? That way units that support it get reloaded correctly and others simply restart to grab a new configuration.

How would you like to proceed from here?

**Comment by secretshardul** [comment]
`TryReloadOrRestart` makes sense. I'll test out `ExecReload` and push an update.

**Comment by secretshardul** [comment]
Reload worked after adding a `ExecReload` script. I think we should use `reload_unit` as per the original PR. The command description can be- "reloads a service having an ExecScript". Running `ReloadOrTryRestart` under a `reload` is confusing, instead we can add a separate `restart` command. What are your thoughts?

**Comment by secretshardul** [comment]
https://github.com/servicer-labs/servicer/commit/287f5b956d42ed044d1f94a701d07187f3dedc71

**Comment by flexwie** [comment]
I'm fine both ways.

Using `ReloadOrTryRestart` would make sure that the goal of reloading the application is reached, but it would be weird for users with experience in systemd that don't want to restart their app (potentially causing downtime).

If we decide to stick with `reload_unit`, we should catch the missing-target error and make it more verbose.
