### ISSUE TITLE
I get a GLIBC error on Ubuntu 20 

### ISSUE THREAD

**Issue by ethereumdegen** [servicer-labs/servicer#9]
/libc.so.6: version `GLIBC_2.34' not found

when trying to run help with teh binary

**Comment by secretshardul** [comment]
Error on `ser --help`? Can you tell me about your

- Servicer version (`ser --version`)
- Operating system
- Did install the binary or built from source with cargo?

**Comment by rizrmd** [comment]
I had same issue,
ubuntu  20.04 by default has glibc 2.31. You can upgrade it using:

```
apt-get install gawk bison gcc make -y
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.34.tar.gz
tar -zxvf glibc-2.34.tar.gz && cd glibc-2.34
mkdir glibc-build && cd glibc-build
../configure --prefix=/opt/glibc
make
make install
```

**Comment by rizrmd** [comment]
But I hope servicer has binary compiled with glibc 2.31. So I don't have to install entire rust toolchain or upgrading my glibc.

**Comment by secretshardul** [comment]
The compiled binary picks the libc version from the system where the code was compiled. `GLIBC_2.34` could be coming from the Github worker. @ethereumdegen @rizrmd can you try building from source using `cargo install servicer`?

[From stackoverflow](https://stackoverflow.com/a/69010071/7721443)

> Per the issue: https://github.com/rust-lang/rust/issues/57497 - there's no way to tell the Rust compiler to link a different library other than the one installed on the system.

> This means I have to compile the binary on a system that has a less recent version of libc6 installed...
